language: c++
dist: xenial
sudo: required

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
    - cmake
    - libluajit-5.1-dev
    - libfreetype6-dev
    - libpulse-dev
    - libsdl2-dev
    - libopenal-dev
    - libmodplug-dev
    - libmpg123-dev
    - libogg-dev
    - libvorbis-dev
    - libtheora-dev

before_install:
- sudo apt-get update –-fix-missing # Travis support tells me to add this.

script:
  - cmake -Bbuild -H.
  - cmake --build build --config Release
