name: livesim3-love
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cc: [gcc, clang]
        cxx: [g++, clang++]
        exclude:
        - cc: gcc
          cxx: clang++
        - cc: clang
          cxx: g++
    steps:
    - name: Update APT
      run: sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo apt-get install --assume-yes build-essential autotools-dev automake libtool pkg-config \
                                          libfreetype6-dev libluajit-5.1-dev libsdl2-dev libopenal-dev \
                                          libogg-dev libvorbis-dev libmodplug-dev libmpg123-dev libtheora-dev \
                                          libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Configure
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=$PWD/installdir -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --target install -j$(nproc)
    # TODO: Artifacts
  windows-os:
    runs-on: windows-2019
    strategy:
      matrix:
        target: [win32, win64]
    env:
      FFMPEG_VERSION: "5.0.1"
    steps:
    - name: Clone Megasource
      uses: actions/checkout@v3
      with:
        path: megasource
        repository: love2d/megasource
        ref: main
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: megasource/libs/love
        submodules: true
    - name: Download FFmpeg Development Libraries
      shell: cmd
      if: ${{ matrix.target == 'win64' }}
      run: curl -Lo ffmpeg-dev.7z https://github.com/GyanD/codexffmpeg/releases/download/%FFMPEG_VERSION%/ffmpeg-%FFMPEG_VERSION%-full_build-shared.7z
    - name: Extract FFmpeg Development Libraries
      shell: cmd
      if: ${{ matrix.target == 'win64' }}
      run: 7z x ffmpeg-dev.7z
    - name: Configure
      shell: cmd
      env:
        WINDOWS_TARGET: ${{ matrix.target }}
      run: |
        set BUILD_TARGET=Win32
        set LS2X_LIBAV_FLAG= 
        if %WINDOWS_TARGET% == win64 (
            set BUILD_TARGET=x64
            set LS2X_LIBAV_TARGET=-DLS2X_LIBAV_INCLUDE_DIR=%CD%\ffmpeg-%FFMPEG_VERSION%-full_build-shared\include
        )
        cmake -Bbuild -Smegasource -T v141 -A %BUILD_TARGET% %LS2X_LIBAV_TARGET% -DCMAKE_INSTALL_PREFIX=%CD%\installdir
    - name: Build
      shell: cmd
      run: cmake --build build --config Release --target install -j2
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: livesim3-love-${{ matrix.target }}
        path: installdir
