name: livesim3-love
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
        cxx: [g++, clang++]
        exclude:
        - cc: gcc
          cxx: clang++
        - cc: clang
          cxx: g++
    steps:
    - name: Update APT
      run: sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo apt-get install --assume-yes build-essential autotools-dev automake libtool pkg-config \
                                          libfreetype6-dev libluajit-5.1-dev libsdl2-dev libopenal-dev \
                                          libogg-dev libvorbis-dev libmodplug-dev libmpg123-dev libtheora-dev \
                                          libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update Submodule
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Configure
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=$PWD/installdir -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --target install # -j2 is not possible, CMake too old.
  windows-os:
    runs-on: windows-2016
    strategy:
      matrix:
        target: [win32, win64]
    steps:
    - name: Clone Megasource
      uses: actions/checkout@v2
      with:
        path: megasource
        repository: love2d/megasource
        ref: master
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: megasource/libs/love
    - name: Update Submodule
      shell: cmd
      run: |
        cd megasource\libs\love
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Download FFmpeg Development Libraries
      shell: powershell
      env:
        TARGETFF: ${{ matrix.target }}
      run: |
        wget -Uri https://ffmpeg.zeranoe.com/builds/$ENV:TARGETFF/dev/ffmpeg-4.0-$ENV:TARGETFF-dev.zip -OutFile ffmpeg-dev.zip
        7z x ffmpeg-dev.zip
    - name: Configure
      shell: cmd
      env:
        TARGETFF: ${{ matrix.target }}
      run: |
        set BUILD_TARGET=Win32
        if %TARGETFF% == win64 set BUILD_TARGET=x64
        cmake -Bbuild -Hmegasource -T v141 -A %BUILD_TARGET% -DLS2X_LIBAV_INCLUDE_DIR=%CD%\ffmpeg-4.0-%TARGETFF%-dev\include -DCMAKE_INSTALL_PREFIX=%CD%\installdir
    - name: Build
      shell: cmd
      run: cmake --build build --config Release --target install -j2
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: livesim3-love-${{ matrix.target }}
        path: installdir
